### ISSUE TITLE
fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by tjoskar** [tokozedg/sman#12]
Hi,

I just installed `sman` (by `bash -c "$(curl https://raw.githubusercontent.com/tokozedg/sman/master/install.sh)"`) and the installation seemed to work fine, however, when I run `s ls` after the installation I got the following error:
```
❯ s ls
fatal error: unexpected signal during runtime execution
[signal 0xb code=0x1 addr=0x395880f3e42a pc=0x1be230]

goroutine 1 [running]:
runtime.throw(0x3ca0c0, 0x2a)
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/panic.go:527 +0x90 fp=0xc820103988 sp=0xc820103970
runtime.sigpanic()
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/sigpanic_unix.go:12 +0x5a fp=0xc8201039d8 sp=0xc820103988
sync.(*Pool).Get(0x50f940, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/sync/pool.go:101 +0x40 fp=0xc820103a28 sp=0xc8201039d8
fmt.newPrinter(0xc820064ec0)
	/usr/local/Cellar/go/1.5.3/libexec/src/fmt/print.go:133 +0x27 fp=0xc820103a68 sp=0xc820103a28
fmt.Sprintln(0xc820103bb8, 0x3, 0x3, 0x0, 0x0)
	/usr/local/Cellar/go/1.5.3/libexec/src/fmt/print.go:270 +0x28 fp=0xc820103ab8 sp=0xc820103a68
log.(*Logger).Println(0xc82007c230, 0xc820103bb8, 0x3, 0x3)
	/usr/local/Cellar/go/1.5.3/libexec/src/log/log.go:182 +0x35 fp=0xc820103b00 sp=0xc820103ab8
github.com/spf13/viper.(*Viper).AddConfigPath(0xc8200fa0e0, 0x35d158, 0x5)
	/Users/Tornike/gocode/src/github.com/spf13/viper/viper.go:323 +0x23a fp=0xc820103bf0 sp=0xc820103b00
github.com/spf13/viper.AddConfigPath(0x35d158, 0x5)
	/Users/Tornike/gocode/src/github.com/spf13/viper/viper.go:319 +0x37 fp=0xc820103c10 sp=0xc820103bf0
github.com/tokozedg/sman/lib.initConfig()
	/Users/Tornike/gocode/src/github.com/tokozedg/sman/lib/root.go:46 +0xc8 fp=0xc820103c98 sp=0xc820103c10
github.com/spf13/cobra.(*Command).preRun(0x50a8e0)
	/Users/Tornike/gocode/src/github.com/spf13/cobra/command.go:595 +0x5b fp=0xc820103cd0 sp=0xc820103c98
github.com/spf13/cobra.(*Command).execute(0x50a8e0, 0x533be8, 0x0, 0x0, 0x0, 0x0)
	/Users/Tornike/gocode/src/github.com/spf13/cobra/command.go:542 +0x478 fp=0xc820103de8 sp=0xc820103cd0
github.com/spf13/cobra.(*Command).ExecuteC(0x50aae0, 0x50a8e0, 0x0, 0x0)
	/Users/Tornike/gocode/src/github.com/spf13/cobra/command.go:656 +0x56b fp=0xc820103ef8 sp=0xc820103de8
github.com/spf13/cobra.(*Command).Execute(0x50aae0, 0x0, 0x0)
	/Users/Tornike/gocode/src/github.com/spf13/cobra/command.go:615 +0x2d fp=0xc820103f20 sp=0xc820103ef8
main.main()
	/Users/Tornike/gocode/src/github.com/tokozedg/sman/main.go:8 +0x23 fp=0xc820103f40 sp=0xc820103f20
runtime.main()
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/proc.go:111 +0x2b0 fp=0xc820103f90 sp=0xc820103f40
runtime.goexit()
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1 fp=0xc820103f98 sp=0xc820103f90

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/Cellar/go/1.5.3/libexec/src/runtime/asm_amd64.s:1721 +0x1
```

I'm on Mac OS 10.13 (high sierra). I'm I missing something? Thanks!

**Comment by ickc** [comment]
You need to install sman from go, using `go get -v github.com/tokozedg/sman`. High Sierra isn't supported by the precompiled binary.

Edit: it is very easy to install go: `brew install go`. Homebrew is highly recommended if not used yet.

**Comment by tjoskar** [comment]
It seems like High Sierra is supported (by the precompiled binary) now. 
Thanks and keep up the good work!
